### PR TITLE
Add support for translations in in-repo addons

### PR DESCRIPTION
**Pull request by robinborst95**
In our codebase I tried out this addon and I realized that in-repo addons were not supported yet (already [issued](https://github.com/simplabs/ember-intl-analyzer/issues/5) a while ago). It seemed easy to add though, so I gave it a try to get it working for us at least. I got it to work, but before I look into adding tests, let me know if this is a good approach and if maybe more use cases with in-repo addons should be supported.

~Note: I don't know if running the tests needs to be explicitly allowed because this is my first PR here, but locally the tests still pass at least.~ I added a test already as I was curious how the tests worked, so now there is proof it works :)

### CODE REVIEW

**Comment by Mikek2252** [comment]
The changes look fine to me, but i'm not sure if the test case is correctly testing your changes. I think the test case should correctly catch whether there is unused translations with in the in-repo addon and also checking that an addon translations that is used in the app is not considered unused.

Also a question, would it better to run `ember-intl-analyzer` independently in that inrepo addon unless you know you will exporting those translations from the addon but not using them in the addon.

**Comment by robinborst95** [comment]
@Mikek2252 I'm not sure if I fully understand what you're saying, but maybe it's good that I explain my thoughts behind it. In our codebase we mainly use in-repo addons for the separation of concerns, so as if it's normal `app` code, but then located in `lib`. So, files in these addons use translations (and other things like components) that are in `app` and vice versa (although limited). For this reason we treat unused and missing translation in `app` in the same way as the in-repo addons, and that's also what I assumed for this PR, so adding the app and in-repo addon files together to look for missing and unused translations.

For the test case I didn't mix it indeed though, so in `app` I didn't use translations from the in-repo addon, and vice versa, so the tests wouldn't catch this when finding the in-repo addons would fail in the future, so I'll add that then :+1: (I think that's what you meant).

To answer your question about running it independently in the in-repo addon: I understand the question, but I think that is not necessarily desired (, at least not in our codebase). As in-repo addons are only used in the app that they're in, it makes sense that they can depend on translations that are not in the addon, so then it makes less sense to mark such translations as missing. If desired (and if support for `addon` next to `app` is added), you can always still run it independently in the addon of course, that just behaves as if you're running it in the `app` itself.

**Comment by Mikek2252** [comment]
@robinborst95 Yeah that seems reasonable enough was more curiosity. As for the test cases i was thinking you may want one that checks the command fails when : 
- a translation that is defined in the in-repo addon but is unused 
-  that a translations that is used in the inrepo addon but is missing.

**Comment by robinborst95** [comment]
@Mikek2252 good suggestions, I've added them :+1:

**Review by Mikek2252 — APPROVED** [review]
Hey, sorry i have been busy this week, but LGTM. I will check out your other PR's before i create a release if i have any comments i will make a release so you dont need to wait to use the changes

**Comment by Mikek2252** [comment]
So it looks like an update to eslint 8 got merged which is why the node10 tests are failing, I will create a breaking release to officially drop support for node 10 then i will merge this

**Pull request merged**
